apiVersion: v1
kind: Secret
metadata:
  name: notifications-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: "c2VjcmV0"
  TWILLO_ACCOUNT_SID: "QUNiYjhhM2FkNTNhZGQxNGY2MzkwYzU0MWRhZThiNjAzNw=="
  TWILLO_AUTH_TOKEN: "YmVkNGQwYTYwMDY5MzI3ODkzZDAyYzIwNTJiZDRkNGY="
  TWILLO_PHONE_NUMBER: "KzE4NDgzNDU1MzE1"
  EMAIL_FROM: "c2hvcGx5LnJr"
  EMAIL_PORT: "NTg3"
  EMAIL_USERNAME: "ODg4YzE4YTQ0ZmUxYzM="
  EMAIL_PASSWORD: "MzhkMjM3NmU4ZTBkZjM="
  EMAIL_HOST: "c2FuZGJveC5zbXRwLm1haWx0cmFwLmlv"
