apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template: 
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ryankaleligabriel/order:latest
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/order/health
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/order/health
              port: 5003
            initialDelaySeconds: 5
            periodSeconds: 10
