apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template: 
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ryankaleligabriel/order:latest
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/orders/health
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/orders/health
              port: 5003
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec: 
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003


---

apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: "c2VjcmV0"


--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  NODE_ENV: "development"
  SERVICE_ORDER: "ORDER"
  PORT_ORDER: "5003"
  USER_URL: "http://user-service:5000"
  ORDER_URL: "http://order-service:5003"
  PAYMENT_URL: "http://payment-service:5002"
  PRODUCT_URL: "http://product-service:5001"
  NOTIFICATIONS_URL: "http://notifications-service:5004"
  CART_URL: "http://cart-service:5005"
  POSTGRES_DB: "shoply"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "shoply"
  POSTGRES_HOST: "db-service"