version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: shoply_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 35s
      retries: 5

  user:
    build: ./user
    container_name: user_service
    ports:
      - "5000:5000"
    environment:
      SERVICE_USER: ${SERVICE_USER}
      PORT_USER: ${PORT_USER}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  payment:
    build: ./payment
    container_name: payment_service
    ports:
      - "5002:5002"
    environment:
      SERVICE_PAYMENT: ${SERVICE_PAYMENT}
      PORT_PAYMENT: ${PORT_PAYMENT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  product:
    build: ./product
    container_name: product_service
    ports:
      - "5001:5001"
    environment:
      SERVICE_PRODUCT: ${SERVICE_PRODUCT}
      PORT_PRODUCT: ${PORT_PRODUCT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  order:
    build: ./order
    container_name: order_service
    ports:
      - "5003:5003"
    environment:
      SERVICE_ORDER: ${SERVICE_ORDER}
      PORT_ORDER: ${PORT_ORDER}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  notifications:
    build: ./notifications
    container_name: notifications_service
    ports:
      - "5004:5004"
    environment:
      SERVICE_NOTIFICATION: ${SERVICE_NOTIFICATION}
      PORT_NOTIFICATION: ${PORT_NOTIFICATION}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  cart:
    build: ./cart
    container_name: cart_service
    ports:
      - "5005:5005"
    environment:
      SERVICE_CART: ${SERVICE_CART}
      PORT_CART: ${PORT_CART}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user
      - product
      - payment
      - cart
      - order
      - notifications

volumes:
  postgres_data:
