version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: shoply_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 35s
      retries: 5

  user:
    build: ./user
    container_name: user_service
    env_file:
      - ./user/.env
    ports:
      - "3001:3001"
    environment:
      SERVICE: ${SERVICE}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  payment:
    build: ./payment
    container_name: payment_service
    env_file:
      - ./payment/.env
    ports:
      - "3002:3002"
    environment:
      SERVICE: ${SERVICE}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  product:
    build: ./product
    container_name: product_service
    env_file:
      - ./product/.env
    ports:
      - "3003:3003"
    environment:
      SERVICE: ${SERVICE}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  order:
    build: ./order
    container_name: order_service
    env_file:
      - ./order/.env
    ports:
      - "3004:3004"
    environment:
      SERVICE: ${SERVICE}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  notifications:
    build: ./notifications
    container_name: notifications_service
    env_file:
      - ./notifications/.env
    ports:
      - "3005:3005"
    environment:
      SERVICE: ${SERVICE}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  cart:
    build: ./cart
    container_name: cart_service
    env_file:
      - ./cart/.env
    ports:
      - "3006:3006"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user
      - product
      - payment
      - cart
      - order
      - notifications

volumes:
  postgres_data:
