apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: "c2VjcmV0"
  SAFARICOM_CONSUMER_KEY: "TUtlRVBlOEZCMU12WW9EeXl6WjhWeFcwWE95MDZPV0pudVhLSjhCdTdzZm9jT2ZU"
  SAFARICOM_CONSUMER_SECRET: "cUtuczM1QVpEbnlTUXhWZ3pxUDF1cmtheW5sVmwyYUdqanVjYng2STBPSkZDWm9STVhNWjA2eUdOSjBpdUV6ZA=="
  BUSINESS_SHORTCODE: "MTc0Mzc5"
  PASS_KEY: "YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOQ=="
  STRIPE_PUBLISHABLE_KEY: "cGtfdGVzdF81MVFsb2xKTHZJT29hNFlPcXB2MmhGd2JQVFB5aUJhdGU3WEZxRDlLbUNmTWNEUURoMkV5OFdON0ZZZnRvVGcySTlZUFlDWDY3T1V0RndiMnFUNGpicVJUaTAwWWxYV1gzT0U="
  STRIPE_SECRET_KEY: "c2tfdGVzdF81MVFsb2xKTHZJT29hNFlPcXhoa0w4Zm4yNkNZWldia2hZVkNEZTJqU3FzSHBaUFhPd3A4S29ON2JNYXZ0TUFTdDRoMXNNTDVjUHQ2SnltZktSdU1icFAxVjAwWElNbVlHQ1U="  

