apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments-service
  template:  # <-- Moved outside selector
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: ryankaleligabriel/payments:latest
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: payments-config
            - secretRef:
                name: payments-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/payments/health
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/payments/health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
