apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:  # <-- Moved outside selector
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ryankaleligabriel/product:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: product-config
            - secretRef:
                name: product-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/products/health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/products/health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec: 
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001


--- 

apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: "c2VjcmV0"
 
--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  NODE_ENV: "development"
  SERVICE_PRODUCT: "PRODUCT"
  PORT_PRODUCT: "5001"
  USER_URL: "http://user-service:5000"
  ORDER_URL: "http://order-service:5003"
  PAYMENT_URL: "http://payment-service:5002"
  PRODUCT_URL: "http://product-service:5001"
  NOTIFICATIONS_URL: "http://notifications-service:5004"
  CART_URL: "http://cart-service:5005"
  POSTGRES_DB: "shoply"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "shoply"
  POSTGRES_HOST: "db-service"