apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:  # <-- Moved outside selector
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ryankaleligabriel/product:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: product-config
            - secretRef:
                name: product-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/product/health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/product/health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
