server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# clients.url: This is the Loki endpoint where Promtail will send the logs.
clients:
  - url: http://loki:3100/loki/api/v1/push

# scrape_configs: This section defines where Promtail should look for logs. In your case, it's /var/log/*.log.
scrape_configs:
  - job_name: app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app_logs
          __path__: "/var/log/*.log"
