apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
data:
  JWT_SECRET: "eW91ci1zZWNyZXQtdmFsdWU="
  GOOGLE_CLIENT_SECRET: "R09DU1BYLVplRGVQeWRFUDFfUFJTbF9GY0llaUVWemMyUFg="
  POSTGRES_PASSWORD: "c2VjcmV0"
  APP_PASSWORD: "bGJudCBzdHR2IHZnaXYgcGl3dg=="
