apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  NODE_ENV: "development"
  SERVICE_USER: "USER"
  PORT_USER: "5000"
  JWT_EXPIRES_IN: "30d"
  JWT_COOKIE_EXPIRES_IN: "30"
  GOOGLE_CLIENT_ID: "410109864972-s2jpi6o39mfdfme51rse8krggndroclm.apps.googleusercontent.com"
  GOOGLE_OAUTH_URL: "https://accounts.google.com/o/oauth2/v2/auth"
  GOOGLE_ACCESS_TOKEN_URL: "https://oauth2.googleapis.com/token"
  GOOGLE_TOKEN_INFO_URL: "https://oauth2.googleapis.com/tokeninfo"
  USER_URL: "http://user-service:5000"
  ORDER_URL: "http://order-service:5003"
  PAYMENT_URL: "http://payment-service:5002"
  PRODUCT_URL: "http://product-service:5001"
  NOTIFICATIONS_URL: "http://notifications-service:5004"
  CART_URL: "http://cart-service:5005"
  POSTGRES_DB: "shoply"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "shoply"
  POSTGRES_HOST: "db-service"