apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:  # <-- Moved outside selector
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ryankaleligabriel/user:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/users/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/users/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
